FROM python:3.7-slim

ENV PROJECT_HOME=/app

WORKDIR /app

COPY resources/web /app/
COPY models /app/models
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5003

CMD ["python3", "predict_flask.py"]
