FROM bitnami/spark:3.5.3

ENV PROJECT_HOME=/app

WORKDIR /home/elena.moyano/practica_creativa

COPY flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar \
     flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar
     
COPY models /home/elena.moyano/practica_creativa/models

EXPOSE 4040

CMD ["spark-submit", \
     "--master", "local[*]", \
     "--class", "es.upm.dit.ging.predictor.MakePrediction", \
     "--packages", \
       "org.mongodb.spark:mongo-spark-connector_2.12:10.4.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3", \
     "/home/elena.moyano/practica_creativa/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar"]
